version: "3"
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:7.4-fpm
    volumes:
       - ./:/var/www
    container_name: app_test
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    container_name: webserver_test
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

  #Mariadb Service
  db:
    image: mariadb:10.5
    container_name: db_test
    volumes:
      - "dbdata:/var/lib/mysql"
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: doctoreto-voucher-test
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      TZ: Asia/Tehran
    networks:
      - app-network

  pma:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin_test
      restart: unless-stopped
      ports:
       - '8080:80'
      networks:
       - app-network
      environment:
        PMA_HOST: db

#Docker Networks
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local
